# Clean and don't fail
install:
  - rm -rf docs

# Build the website
script:
  - ./exec/hugo -t arabica
  - cp CNAME docs/

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
